function [U,T] = autoGen_pendubotEnergy(q1,q2,dq1,dq2,m1,m2,g,l1,l2)
%autoGen_pendubotEnergy
%    [U,T] = autoGen_pendubotEnergy(Q1,Q2,DQ1,DQ2,M1,M2,G,L1,L2)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    2025-11-14 16:02:17

t2 = cos(q1);
t3 = cos(q2);
U = -g.*m2.*(l1.*t2+l2.*t3)-g.*l1.*m1.*t2;
if nargout > 1
    t4 = sin(q1);
    t5 = dq1.^2;
    t6 = l1.^2;
    T = (m1.*(t2.^2.*t5.*t6+t4.^2.*t5.*t6))./2.0+(m2.*((dq1.*l1.*t2+dq2.*l2.*t3).^2+(dq2.*l2.*sin(q2)+dq1.*l1.*t4).^2))./2.0;
end
end
