function [M11,M12,M21,M22,f1,f2] = autoGen_pendubotDynamics(q1,q2,dq1,dq2,u,m1,m2,g,l1,l2)
%autoGen_pendubotDynamics
%    [M11,M12,M21,M22,F1,F2] = autoGen_pendubotDynamics(Q1,Q2,DQ1,DQ2,U,M1,M2,G,L1,L2)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    2025-11-14 16:02:17

t2 = cos(q1);
t3 = cos(q2);
t4 = sin(q1);
t5 = sin(q2);
t6 = dq1.^2;
t7 = dq2.^2;
t8 = l1.^2;
t9 = l2.^2;
t10 = l1.*t2;
t11 = l2.*t3;
t12 = l1.*t4;
t13 = l2.*t5;
t14 = t6.*t10;
t15 = t7.*t11;
t16 = t6.*t12;
t17 = t7.*t13;
t18 = t10+t11;
t19 = t12+t13;
M11 = -m1.*t2.^2.*t8-m1.*t4.^2.*t8-m2.*t10.*t18-m2.*t12.*t19;
if nargout > 1
    M12 = -m2.*t11.*t18-m2.*t13.*t19;
end
if nargout > 2
    M21 = -m2.*t10.*t11-m2.*t12.*t13;
end
if nargout > 3
    M22 = -m2.*t3.^2.*t9-m2.*t5.^2.*t9;
end
if nargout > 4
    t20 = t14+t15;
    t21 = t16+t17;
    f1 = -u+g.*m1.*t12+g.*m2.*t19-m2.*t18.*t21+m2.*t19.*t20;
end
if nargout > 5
    f2 = g.*m2.*t13-m2.*t11.*t21+m2.*t13.*t20;
end
end
