function [p1,p2,dp1,dp2] = autoGen_pendubotKinematics(q1,q2,dq1,dq2,l1,l2)
%autoGen_pendubotKinematics
%    [P1,P2,DP1,DP2] = autoGen_pendubotKinematics(Q1,Q2,DQ1,DQ2,L1,L2)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    2025-11-14 16:02:17

t2 = cos(q1);
t3 = cos(q2);
t4 = sin(q1);
t5 = sin(q2);
t6 = l1.*t2;
t7 = l1.*t4;
t8 = dq1.*t6;
t9 = dq1.*t7;
t10 = -t6;
p1 = [t7;t10];
if nargout > 1
    p2 = [t7+l2.*t5;t10-l2.*t3];
end
if nargout > 2
    dp1 = [t8;t9];
end
if nargout > 3
    dp2 = [t8+dq2.*l2.*t3;t9+dq2.*l2.*t5];
end
end
